stages:
    - lint
    - build
    - deploy

include:
    - "https://gitlab.ilearned.eu/i-learned/ci-cd/ci-cd-templates/-/raw/main/makefile-build.yml"
    - "https://gitlab.ilearned.eu/i-learned/ci-cd/ci-cd-templates/-/raw/main/prettier.yml"

deploy:
    image: hub.ilearned.eu/i-learned/ci-cd/alpine-sass
    stage: deploy
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - echo 'vm01.eban.eu.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKnJXmNN2/41gmHqLbUE6+R5qG5ycYvj8fe7KVCeneLm2oBY45oN8kmvT9qi+WKZj+hfTikphHRxw+9LxidveL8=' > ~/.ssh/known_hosts
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned-cdn

    only:
        variables:
            - $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
