stages:
  - prod-deploy

prod-deploy-job: 
  stage: prod-deploy  
  script:
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" . deploy@vm01.eban.eu.org:/var/www/ilearned-cdn
  - main